### ISSUE TITLE
BUG: MapViewer sign in issues with Enterprise logins

### ISSUE THREAD

**Issue by paul-gpsit** [anshuman-mathur/AppStudio-Testing#19]
**Application**: AppStudio Desktop | Player | Website 

**Device**: Windows, iPhone 6, Android Samsung tablets

**Operating System**:  Windows 10, iOS 11

**Error Description**:
Not a new thing but just to keep it on your radar (I have mentioned previously on GeoNet). I think there is an issue with Enterprise logins when using the MapView template, where it doesn't sign in properly in subsequent sessions when it "auto signs-in".

**How to reproduce**:
Open MapViewer. Sign in with an Enterprise login. View a secured map (works fine). Force close the app.
Re-open MapViewer. Allow it to "auto sign-in". Attempt to view a secured map. Secured layers don't seem to load. Error message pops up:  'client_id not specified'.

Have tested with a clean template and can reproduce.

![image](https://user-images.githubusercontent.com/14798260/44250200-8acf0180-a247-11e8-8637-246dc3236710.png)

**Comment by paul-gpsit** [comment]
![image](https://user-images.githubusercontent.com/14798260/44893391-2ffcd600-ad2e-11e8-9f32-a6835589c390.png)

**Comment by paul-gpsit** [comment]
[Map Viewer template login fail to do with client_id.zip](https://github.com/anshuman-mathur/AppStudio-Testing/files/2338827/Map.Viewer.template.login.fail.to.do.with.client_id.zip)
This is the Fiddler session from the screenshot above.

**Comment by marikavertzonis** [comment]
issue created https://devtopia.esri.com/Melbourne/MapViewer/issues/367

**Comment by anshuman-mathur** [comment]
The fix is available in the AppStudio 3.3 release.
